#!/bin/bash
# 重投影误差淘汰功能使用示例

echo "=========================================="
echo "重投影误差淘汰功能使用示例"
echo "=========================================="
echo ""

# 示例 1: 严格模式 - 只保留误差 <= 1.0px 的图片
echo "示例 1: 严格模式（高精度标定）"
echo "命令:"
echo "  python robust_tilt_checker_node.py \\"
echo "      --rosbag rosbags/testbag \\"
echo "      --image-topic /left/color/image_raw \\"
echo "      --camera-yaml config/camera_info.yaml \\"
echo "      --rows 15 --cols 15 \\"
echo "      --tag-family tagStandard41h12 \\"
echo "      --tag-size 0.0071 \\"
echo "      --board-spacing 0.065 \\"
echo "      --max-error 1.0 \\"
echo "      --save-images \\"
echo "      --publish-results"
echo ""
echo "效果: 只保留误差 ≤ 1.0px 的图片，适合高精度标定"
echo ""

# 示例 2: 中等模式 - 只保留误差 <= 5.0px 的图片
echo "=========================================="
echo "示例 2: 中等模式（一般应用）"
echo "命令:"
echo "  python robust_tilt_checker_node.py \\"
echo "      --rosbag rosbags/testbag \\"
echo "      --image-topic /left/color/image_raw \\"
echo "      --camera-yaml config/camera_info.yaml \\"
echo "      --rows 15 --cols 15 \\"
echo "      --max-error 5.0 \\"
echo "      --save-images"
echo ""
echo "效果: 只保留误差 ≤ 5.0px 的图片，平衡质量和数量"
echo ""

# 示例 3: 宽松模式 - 只保留误差 <= 10.0px 的图片（默认）
echo "=========================================="
echo "示例 3: 宽松模式（默认）"
echo "命令:"
echo "  python robust_tilt_checker_node.py \\"
echo "      --rosbag rosbags/testbag \\"
echo "      --image-topic /left/color/image_raw \\"
echo "      --camera-yaml config/camera_info.yaml \\"
echo "      --rows 15 --cols 15 \\"
echo "      --max-error 10.0 \\"
echo "      --save-images"
echo ""
echo "效果: 只保留误差 ≤ 10.0px 的图片，保留大部分数据"
echo ""

# 示例 4: 调试模式 - 不淘汰任何图片
echo "=========================================="
echo "示例 4: 调试模式（查看所有误差）"
echo "命令:"
echo "  python robust_tilt_checker_node.py \\"
echo "      --rosbag rosbags/testbag \\"
echo "      --image-topic /left/color/image_raw \\"
echo "      --camera-yaml config/camera_info.yaml \\"
echo "      --rows 15 --cols 15 \\"
echo "      --max-error 1000.0 \\"
echo "      --save-images"
echo ""
echo "效果: 不淘汰任何图片，用于查看误差分布"
echo ""

# 查看结果
echo "=========================================="
echo "查看结果"
echo "=========================================="
echo ""
echo "1. 查看统计报告:"
echo "   cat outputs/robust_apriltag_results/summary_report.txt"
echo ""
echo "2. 查看 JSON 结果:"
echo "   cat outputs/robust_apriltag_results/robust_results.json | jq '.summary'"
echo ""
echo "3. 查看保存的图片:"
echo "   ls -lh outputs/robust_apriltag_results/images/"
echo ""
echo "4. 查看被淘汰的帧（从日志）:"
echo "   grep '淘汰该帧' 日志文件"
echo ""

# 推荐工作流程
echo "=========================================="
echo "推荐工作流程"
echo "=========================================="
echo ""
echo "步骤 1: 先用大阈值运行，查看误差分布"
echo "  python robust_tilt_checker_node.py --max-error 1000.0 --rosbag test.bag"
echo ""
echo "步骤 2: 查看统计报告中的误差统计"
echo "  cat outputs/robust_apriltag_results/summary_report.txt"
echo ""
echo "步骤 3: 根据误差分布设置合适的阈值"
echo "  - 平均误差 < 2px  → 阈值设为 1.0px"
echo "  - 平均误差 2-5px  → 阈值设为 3.0-5.0px"
echo "  - 平均误差 > 5px  → 阈值设为 10.0px"
echo ""
echo "步骤 4: 重新运行并检查淘汰率"
echo "  python robust_tilt_checker_node.py --max-error 3.0 --rosbag test.bag"
echo ""
echo "步骤 5: 调整阈值直到淘汰率在 10-30% 之间"
echo ""

echo "=========================================="
echo "完成！"
echo "=========================================="
